# Generated by Django 3.1.6 on 2021-02-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='first_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='last_name',
            new_name='type_name',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
    ]
