# Generated by Django 3.1.6 on 2021-02-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_auto_20210210_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categorie',
            new_name='category',
        ),
    ]
